debug: true
server:
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: xyz@123
        keyAlias: your_alias
        keyStoreType: PKCS12
spring:
    application:
        name: AppointmentSchedulingSystem
    data:
        mongodb:
            database: AppointmentSchedulingSystem
            host: localhost
            port: 27017