debug: true
server:
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: jenil@1317
        keyAlias: your_alias
        keyStoreType: PKCS12
spring:
    security:
        jwt:
            secret: asdfghjklzxcvbnmqwertyuiopzxcvbnmasdfghjklqwertyuiopMNBVCXZLKJHGFDSAPOIUYTREWQzxcvbnmLKJHGFDIUY
            tokenValidity: 3600
    application:
        name: AppointmentSchedulingSystem
    data:
        mongodb:
            database: AppointmentSchedulingSystem
            host: localhost
            port: 27017