debug: true
server:
    ssl:
        key-store: classpath:AppointmentSchedulingSystem.p12
        key-store-password: xyz@123
        keyStoreType: PKCS12
spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    security:
        jwt:
            secret: asdfghjklzxcvbnmqwertyuiopzxcvbnmasdfghjklqwertyuiopMNBVCXZLKJHGFDSAPOIUYTREWQzxcvbnmLKJHGFDIUY
            tokenValidity: 3600
    application:
        name: AppointmentSchedulingSystem
    data:
        mongodb:
            database: AppointmentSchedulingSystem
            host: localhost
            port: 27017